version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'  # Exposes Adminer on port 8080
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
